image: node:latest

stages:
  - prepare
  - test
  - build
  - publish

.when_package_json:
  rules:
    - changes:
        - package.json

prepare:
  stage: prepare
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm ci
  artifacts:
    paths:
      - node_modules/
  extends:
    - .when_package_json

lint:
  stage: test
  script:
    - npm run lint:no-fix
  extends:
    - .when_package_json

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  extends:
    - .when_package_json

publish:
  stage: publish
  script:
    - npm publish
  extends:
    - .when_package_json