stages:
  - prepare
  - test
  - build
  - publish

prepare:
  stage: prepare
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
  when: manual

lint:
  stage: test
  script:
    - npm run lint:no-fix
  when: manual

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  when: manual

publish:
  stage: publish
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_PUSHER}">.npmrc
    - npm publish --access=public
  when: manual