export enum HorizontalAlign {
  LEFT_OUTER = 'LEFT_OUTER',
  LEFT_CENTER = 'LEFT_CENTER',
  LEFT_INNER = 'LEFT_INNER',
  FILL = 'FILL',
  FILL_MIN = 'FILL_MIN',
  CENTER = 'CENTER',
  RIGHT_INNER = 'RIGHT_INNER',
  RIGHT_CENTER = 'RIGHT_CENTER',
  RIGHT_OUTER = 'RIGHT_OUTER',
}
